### ISSUE TITLE
Allow leading zeros for track and disc

### ISSUE THREAD

**Issue by ghost** [quebin31/muso#5]
**Is your feature request related to a problem? Please describe.**
If you use the ~{discnumber}~{disc} or {track} placeholder, the filename only contains the numbers without a leading zero.

**Describe the solution you'd like**
It would be amazing to have the ability to set an option allow using leading zeros.

Thank you very much for this cool piece of software!

**Comment by quebin31** [comment]
I also thought about this when I was adding those placeholders. I think that adding some sort of *naive* formatting would do it, since adding the leading zeros automatically would require to find all songs that are in a certain album. This should be done every time a new song was added to your folder.

**But** since almost every album nowadays have less than 100 songs (right? haha), it should be enough to add leading zeros until the number got `n` digit length, for example with `n` equal to `2`:

- `2` will become `02`
- `10` will become `10` 

With this in mind, this should be enough:

- [ ] Add a new flag `--leading-zeros/-z` with the possibility to take an integer value, which is going to be the needed length, by default `2` only if the flag is present.
- [ ] Add a new option in config `leading-zeros`, it will receive an integer or a boolean, the value `true` will be interpreted as `2` and `false` as `0`, integer values will be interpreted as integers.

**Comment by quebin31** [comment]
I will add this to format string, something like Rust fmt. For example, to add leading zeros until the number gets 2 digit length you would do `{disc:2} - {track:2}`. This will take some time since this will require a total redesign of that specific part.

**Comment by quebin31** [comment]
@bloomvdomino check out the new version.

**Comment by ghost** [comment]
@quebin31 Works like a charm!
